# Generated by Django 3.2.7 on 2021-09-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', help_text='Изображение профиля', upload_to='avatars'),
        ),
    ]
